[project]
name = "content-pay"
authors = []
description = ""
telemetry = true
cache_dir = ".cache"
requirements = []

[contracts.sip-010-trait-ft-standard]
path = "contracts/sip-010-trait-ft-standard.clar"
clarity_version = 2
epoch = 2.5

[contracts.mock-sbtc-v1]
path = "contracts/mock-sbtc.clar"
clarity_version = 2
epoch = 2.5

[contracts.mock-usdc-v1]
path = "contracts/mock-usdc.clar"
clarity_version = 2
epoch = 2.5

[contracts.pyth-oracle-trait]
path = "contracts/pyth-oracle-trait.clar"
clarity_version = 2
epoch = 2.5

[contracts.mock-pyth-oracle-v1]
path = "contracts/mock-pyth-oracle.clar"
clarity_version = 2
epoch = 2.5

[contracts.content-registry]
path = "contracts/content-registry.clar"
clarity_version = 2
epoch = 2.5