
[project]
name = "content-pay"
authors = []
description = ""
telemetry = true
cache_dir = ".cache"
requirements = []

[contracts.content-registry]
path = "contracts/content-registry.clar"
clarity_version = 2
epoch = 2.5